version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      - MONGODB_URL=mongodb://mongo:27017/temperatureDb
      - PORT=8000
    depends_on:
      - mongo
      - n8n

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - '5678:5678'
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=password
    volumes:
      - ./n8n/workflows:/root/.n8n
    depends_on:
      - mongo

volumes:
  mongo-data:
