import { Temperature } from '../models/temperature.model';

// Process the temperature reading and update or create a new record
export const processReading = async (
  id: string | undefined,
  temperature: number,
  timestamp: Date
) => {
  let status = temperature > 25 ? 'HIGH' : 'NORMAL';

  // If no id is provided, MongoDB will create a new record with an autogenerated _id
  const updatedReading = await Temperature.findOneAndUpdate(
    { _id: id }, // Search by _id
    { status, temperature, timestamp, processedAt: new Date() }, // Update or create new record with new data
    { new: true, upsert: true } // Ensure the record is returned and create if not found
  );

  // Return the updated or created record
  return {
    id: updatedReading._id,
    temperature: updatedReading.temperature,
    timestamp: updatedReading.timestamp,
    status: updatedReading.status,
    processedAt: updatedReading.processedAt,
  };
};
